import type { GuideStep } from './types'

export const guideSteps: GuideStep[] = [
  {
    id: 'm1-map',
    path: '/module1',
    target: 'module1-map',
    title: '先看徽州建筑的空间骨架',
    body: '这一块是整页的中心。颜色、点位和建筑标记一起告诉我们：徽派建筑不是平均散开的，它会沿着城镇、水系、宗族聚落慢慢长出来。先抓住这张地图，后面的图就有了落脚点。',
  },
  {
    id: 'm1-category',
    path: '/module1',
    target: 'module1-category',
    title: '看类型比例，不只看数量',
    body: '这里展示不同建筑类型的占比。它像一张入口清单：祠堂、民居、牌坊、桥梁这些类型各自承担不同的社会角色，合起来才是徽州生活的完整场景。',
  },
  {
    id: 'm1-history',
    path: '/module1',
    target: 'module1-history',
    title: '把时间线拉出来',
    body: '这张图看的是历朝留存变化。不要只盯最高点，真正有意思的是起伏：哪一段建筑活动更集中，往往和商业、宗族、迁徙、地方治理都有关系。',
  },
  {
    id: 'm1-info',
    path: '/module1',
    target: 'module1-info',
    title: '点到建筑后，看故事落地',
    body: '右侧信息面板负责把地图上的点讲成具体对象。你选中一座建筑或一个区域后，这里会补上名称、背景和叙事，让数据不只是点，而是能被记住的地方。',
  },
  {
    id: 'm1-river',
    path: '/module1',
    target: 'module1-river',
    title: '代表作的时间河流',
    body: '底部这条“河流”把重要建筑与事件按年代铺开。彩色标记代表初建、修缮、保护等不同命运——读它就像翻一本微缩的徽州建筑史。',
  },
  {
    id: 'm2-fan',
    path: '/module2',
    target: 'module2-fan',
    title: '从构件入口进入',
    body: '模块二先从扇形入口开始。马头墙、粉墙、天井、屋顶不是孤立部件，它们分别控制轮廓、界面、光风水和屋面姿态。点不同扇面，右侧图表会跟着换。',
    action: { type: 'setFan', key: 'mtq' },
  },
  {
    id: 'm2-mtq-a',
    path: '/module2',
    target: 'module2-chart-a',
    title: '马头墙：先看主图',
    body: '左上是当前构件最核心的那张图。读马头墙时可以先想两件事：它在村落里起什么作用（防火、轮廓），又在单栋建筑上怎么“长”出来。',
    action: { type: 'setFan', key: 'mtq' },
  },
  {
    id: 'm2-mtq-b',
    path: '/module2',
    target: 'module2-chart-b',
    title: '马头墙：关系与类型',
    body: '右上区域常把不同马头墙形式、尺度或关系放在一起比较。看不懂时，先找图例和分组——它往往在回答“哪一种更常见、哪一种更特殊”。',
    action: { type: 'setFan', key: 'mtq' },
  },
  {
    id: 'm2-mtq-c',
    path: '/module2',
    target: 'module2-chart-c',
    title: '马头墙：词云里的关键词',
    body: '词云把文献和口述里的高频词放大。字号越大，说明在描述马头墙时大家越常提到它——比如防火、座头、印斗式等。',
    action: { type: 'setFan', key: 'mtq' },
  },
  {
    id: 'm2-mtq-d',
    path: '/module2',
    target: 'module2-chart-d',
    title: '马头墙：收束到结论',
    body: '右下更适合看总结型图表，把前面零散信息压成趋势或结构。看完前三张图，来这里确认：马头墙最重要的特征到底是什么。',
    action: { type: 'setFan', key: 'mtq' },
  },
  {
    id: 'm2-tj-a',
    path: '/module2',
    target: 'module2-chart-a',
    title: '天井：光与水的入口',
    body: '已为你切到天井主题。左上图表多在讲采光、通风或热环境——天井其实是把自然要素“邀请”进封闭院落的中庭。',
    action: { type: 'setFan', key: 'tj' },
  },
  {
    id: 'm2-tj-d',
    path: '/module2',
    target: 'module2-chart-d',
    title: '天井：总结型读图',
    body: '天井相关的热工或形态总结常放在右下。可以把它理解成“这一构件在科学测量或类型学上的答案”。',
    action: { type: 'setFan', key: 'tj' },
  },
  {
    id: 'm2-fq-a',
    path: '/module2',
    target: 'module2-chart-a',
    title: '粉墙：界面与肌理',
    body: '粉墙是徽派建筑最安静的底色。左上图表可能在比较不同抹灰层次、色彩或工艺——它决定建筑近看时的质感。',
    action: { type: 'setFan', key: 'fq' },
  },
  {
    id: 'm2-wd-a',
    path: '/module2',
    target: 'module2-chart-a',
    title: '屋顶：姿态与形式',
    body: '屋顶决定建筑在天空下的剪影。左上图表常涉及坡度、屋脊、瓦作等——这些细节让同一套白墙黛瓦也有不同的性格。',
    action: { type: 'setFan', key: 'wd' },
  },
  {
    id: 'm3-cards',
    path: '/module3',
    target: 'module3-cards',
    title: '先认识人和书',
    body: '上方卡片把营建人物、文献和作品摆出来。徽派建筑不只是样式史，也是知识传承史：谁记录、谁修造、谁总结，都会影响我们今天怎么理解它。',
  },
  {
    id: 'm3-wood-graph',
    path: '/module3',
    target: 'module3-graph',
    title: '木雕：传承关系网',
    body: '左下关系图把匠人、层级和作品连成网络。线条不是装饰，它在告诉你技艺怎样从一个人、一处地方，扩散成更稳定的地方传统。',
    action: { type: 'setCraft', key: 'wood' },
  },
  {
    id: 'm3-wood-center',
    path: '/module3',
    target: 'module3-center',
    title: '木雕：中间这件“作品”',
    body: '中间大图是当前雕种的代表形象。左右箭头可以切换木雕、石雕、砖雕——引导时会自动帮你切到对应雕种。',
    action: { type: 'setCraft', key: 'wood' },
  },
  {
    id: 'm3-wood-detail',
    path: '/module3',
    target: 'module3-detail',
    title: '木雕：工序与纹样',
    body: '右侧详情区适合慢慢看。工艺步骤、工具、纹样、材料这些细节，正是徽派建筑“耐看”的原因：远看是白墙黛瓦，近看全是手艺。',
    action: { type: 'setCraft', key: 'wood' },
  },
  {
    id: 'm3-stone-graph',
    path: '/module3',
    target: 'module3-graph',
    title: '石雕：传承关系网',
    body: '已切换到石雕。石作更常出现在柱础、栏板、牌坊——关系图里国家级、省级传承人的节点，往往对应重要的石作案例。',
    action: { type: 'setCraft', key: 'stone' },
  },
  {
    id: 'm3-stone-center',
    path: '/module3',
    target: 'module3-center',
    title: '石雕：庄重而耐久',
    body: '石雕作品多强调礼制与纪念性。中间展示图配合下方简介，帮你建立“石雕在徽州外部空间里扮演什么角色”的印象。',
    action: { type: 'setCraft', key: 'stone' },
  },
  {
    id: 'm3-stone-detail',
    path: '/module3',
    target: 'module3-detail',
    title: '石雕：读工具与纹样',
    body: '右侧可切换工序、工具、纹样等标签。读石雕时不妨留意：粗加工与精修如何分工，纹样又如何服务祠堂、牌坊的礼制语义。',
    action: { type: 'setCraft', key: 'stone' },
  },
  {
    id: 'm3-brick-graph',
    path: '/module3',
    target: 'module3-graph',
    title: '砖雕：门楼上的叙事',
    body: '砖雕多集中在门罩、门楼。关系图里与砖雕相关的传承人、作品节点，往往对应徽州民居“门面”上的精细叙事。',
    action: { type: 'setCraft', key: 'brick' },
  },
  {
    id: 'm3-brick-center',
    path: '/module3',
    target: 'module3-center',
    title: '砖雕：层次与透空',
    body: '砖雕要在青砖上做出多层景深，对胎料和刀路要求很高。中间图像配合简介，展示砖雕作为“立面雕塑”的特质。',
    action: { type: 'setCraft', key: 'brick' },
  },
  {
    id: 'm3-brick-detail',
    path: '/module3',
    target: 'module3-detail',
    title: '砖雕：从制坯到挂镶',
    body: '右侧工序标签会带你走过制坯、放样、打坯、精雕、拼装等步骤。砖材易崩，所以砖雕匠人的“稳”和“准”尤其重要。',
    action: { type: 'setCraft', key: 'brick' },
  },
]
